### ISSUE TITLE
EtherCIS - Clinical Query - Christian to support "match" rather than "like"?

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/Ripple-openEHR#4]
Christian

**Comment by ethercis** [comment]
Done for the following statements:

- matches
- like
- ilike

(icing on the cake: now supports LIMIT ... OFFSET ...)

GitHub and test server updated

**Comment by tony-shannon** [comment]
many thanks @ethercis 
@freshehr can you confirm this is working for our current clinical query needs please?

**Comment by freshehr** [comment]
`select a/uid/value as uid, a/name/value as name from EHR e contains COMPOSITION a where a/name/value matches { 'Adverse reaction list' , 'Problem list' } ` is working.

Order and limit are working but the order in AQL syntax is wrong - should

offset 0 limit 5 

NOT limit 5 offset 0

**Comment by tony-shannon** [comment]
thanks @freshehr 
Who should action that please?

**Comment by ethercis** [comment]
OK I will adapt the grammar. Please note OFFSET and LIMIT and currently not specified in the AQL spec. The order (limit/offset) is the one currently used by SQL spec...

**Comment by tony-shannon** [comment]
thanks @ethercis

**Comment by freshehr** [comment]
@ethercis - sure, this is a Marand extension.

**Comment by PhilBarrett** [comment]
@ethercis Please could I ask for an update on this, cheers.

**Comment by PhilBarrett** [comment]
Confirmed by @freshehr as being resolved
