### ISSUE TITLE
EtherCIS - Data tidy up - Christian to provide script to wipe DB to clean state

### ISSUE THREAD

**Issue by PhilBarrett** [RippleOSI/Ripple-openEHR#7]
CC

**Comment by ethercis** [comment]
Done, see documentation @ https://github.com/ethercis/ethercis/blob/master/doc/DB%20administration.md
Function purge_db() deployed on the test server as well

**Comment by tony-shannon** [comment]
thanks @ethercis 
@freshehr please confirm you're happy for this to be closed
T

**Comment by freshehr** [comment]
That's fine but it would be really helpful to have this exposed as an API
call (separate admin authorisation) - Marand provide a truncate() call

{{openEhrApi}}/ehrscape-manager/rest/domain/{{domainSystemId}}/truncate
as that makes it easier to truncate and re-provision from a service layer.

Ian

Dr Ian McNicoll
mobile +44 (0)775 209 7859
office +44 (0)1536 414994
skype: ianmcnicoll
email: ian@freshehr.com
twitter: @ianmcnicoll


Co-Chair, openEHR Foundation ian.mcnicoll@openehr.org
Director, freshEHR Clinical Informatics Ltd.
Director, HANDIHealth CIC
Hon. Senior Research Associate, CHIME, UCL

**Comment by ethercis** [comment]
I understand what you mean , but this is really a dangerous hack (since nobody does care to do a DB backup before doing the DB purge... pretty usual IMO). I much prefer to keep it for the happy initiated few who are supposed to know what they are doing, hence as an administrative - logged - operation.

**Comment by freshehr** [comment]
ok - understood. Park for now.

Ian

**Comment by PhilBarrett** [comment]
@freshehr - are you ok for this to be closed on that basis.

**Comment by freshehr** [comment]
Agreed - in retrospect ;)

Ian
