### ISSUE TITLE
 generic PROMs template

### ISSUE THREAD

**Issue by tony-shannon** [RippleOSI/Ripple-openEHR#9]
Hi @freshehr 

Can we get an update on this template please?

https://github.com/RippleOSI/Ripple-openEHR/blob/master/docs/bindings/Current%20Ripple%20Headings/PROMS/proms.md

As per recent discussion, needs to be as simple as possible with some interEHR linkage

thanks
T

**Comment by tony-shannon** [comment]
explanation of the inter EHR linkage we are after;
![image](https://user-images.githubusercontent.com/939996/37526389-1b0a6d9c-2927-11e8-9a43-2a7444bb4816.png)

**Comment by freshehr** [comment]
Made significant progress... Figured out how do to linkages (not currently supported in Ethercis but I have a workaround).

Template updated to include 'Type of Proms' I have kept the procedure inline (alongside a linkto its original source)./ Up for discussion but there is a case (clinicak and technical) for carrying both.

The templates are done and up in both CDRs. Data example below. Just need to get this documented, as there are now a few moving parts, that will need explained. Will get onto that later this afternoon.

```
{
"ctx/composer_name": "Dr Tony Shannon",
"ctx/health_care_facility|id": "999999-345",
"ctx/health_care_facility|name": "Home",
"ctx/id_namespace": "NHS-UK",
"ctx/id_scheme": "2.16.840.1.113883.2.1.4.3",
"ctx/language": "en",
"ctx/territory": "GB",
"ctx/time": "2017-11-14T00:11:02.518+02:00",
   "generic_proms/context/proms_type": "Foot and ankle PROMS - pre-op assessment",
   "generic_proms/context/ecis_procedure_link": "ehr:///3cd3bef6-d180-4d73-91c7-fb4ea231bb1b::hcbox.oprn.ehrscape.com::1/content/items[uid/value='140413da-b1d4-41c4-a3f3-d86abe47a9f1']",
   "generic_proms/procedure/ism_transition/current_state|code": "245",
   "generic_proms/procedure/ism_transition/careflow_step|code": "at0047",
   "generic_proms/procedure/procedure_name|value": "Excision of cataract",
   "generic_proms/procedure/procedure_name|terminology": "SNOMED-CT",
   "generic_proms/procedure/procedure_name|code": "54885007",
   "generic_proms/sf-36:0/a1._health_in_general|code": "at0009",
   "generic_proms/sf-36:0/a2._health_compared_to_1_year_ago|code": "at0017",
   "generic_proms/sf-36:0/limitations_to_activities_during_typical_day/a3._vigorous_activies|code": "at0022",
   "generic_proms/sf-36:0/limitations_to_activities_during_typical_day/a4._moderate_activies|code": "at0027",
   "generic_proms/sf-36:0/limitations_to_activities_during_typical_day/a5._lifting_or_carrying_groceries|code": "at0030",
   "generic_proms/pain_vas/pain_vas:0/pain_scale": 81
}
```

**Comment by tony-shannon** [comment]
great thanks Ian
We were planning to persist in EtherCIS, who needs to do what re workaround?
T

**Comment by freshehr** [comment]
Done - I have co-opted another element in the composition to carry the link target . Not 'proper openEHR' but it will do for now. I have submitted an issue re LINK but I don't consider it a priority.

**Comment by tony-shannon** [comment]
ok thanks Ian
Let us know when thats been uploaded for Rob to work from
thanks
T

**Comment by freshehr** [comment]
Should be all ready for Rob now see https://github.com/RippleOSI/Ripple-openEHR/commit/ab13eba5e81c5fc01633e4872df20a98e62101fc

**Comment by tony-shannon** [comment]
Thanks Ian
